### ISSUE TITLE
Functions defined on multiple lines not detected 

### ISSUE THREAD

**Issue by hallee** [pixel-foundry/nova-swift#4]
https://github.com/pixel-foundry/nova-swift/blob/81735697222b37c83cd292aa4d054d1434696f23/Swift.novaextension/Syntaxes/Swift.xml#L159

It seems like Nova's `<starts-with>` `<expression>` doesn't detect on multiple lines. The regex for function starts seems correct to me, but any newline character breaks it.

These are both valid Swift but only the first is detected:

```swift
func myFunc() {  }

func
myFunc() { }
```

I haven't figured out a way to handle this on multiple lines. `<starts-with>` must include the opening brace, otherwise this conflicts with other syntax definitions like closures.

**Comment by logancollins** [comment]
Hello Hal,

This is correct. Expressions do not support matching between multiple lines. This is a behavior of the underlying regular expression engine that Nova uses (PCRE2).

I believe it would be possible for us to support this type of behavior through the use of anchored match lines in regex, but we currently do not expose that ability to syntax grammars in such a way. I will file a ticket in our internal tracker to investigate further.

For the time being, I believe the only option for this scenario would be for the `starts-with` expression to match just `\b(func)\b` and begin a scope that in turn parses the components inside, and using an `ends-with` expression that relies on a lookbehind (such as `(?<\})`) to end the function definition. This is clearly not the best or most reliable, so I will see if we can get a better option available in a release soon.

Logan

**Comment by logancollins** [comment]
@hallee Just wanted to update you on things from our side a bit: We've implemented support for a more anchored / ordered form of parsing that I think would allow you to do everything you described here. We hope to have support for it in Nova 4, which will likely be coming in early December.

**Comment by hallee** [comment]
@logancollins Thanks for the update! I got this working with lookaheads but I might revisit when those changes drop.

Thanks for your work on Nova! I love how quickly it's getting updates. I haven't even bothered installing Sublime or VSCode on my M1 MacBook yet. It was amazing to see Nova ready for Apple Silicon on day 1 👍
